"""movies: anadir poster_path y backdrop_path

Revision ID: 81ea96db5f0d
Revises: 016efc22bda5
Create Date: 2026-07-12 17:40:43.965565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ea96db5f0d'
down_revision: Union[str, Sequence[str], None] = '016efc22bda5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('poster_path', sa.String(length=255), nullable=True))
    op.add_column('movies', sa.Column('backdrop_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'backdrop_path')
    op.drop_column('movies', 'poster_path')
    # ### end Alembic commands ###
